import { DiscountType, ProductType, type Product } from '@eiwittens/types';

const baseProduct = {
    store: 'Test Store',
    url: 'https://example.test/product',
    subtypes: [],
    enabled: true,
    scrape_enabled: true,
    out_of_stock: false,
    enabled_top10: true,
    only_in_store: false,
    scraper: [],
    ingredients: [],
    discount_type: DiscountType.None,
} satisfies Partial<Product>;

export const testProducts: Product[] = [
    {
        ...baseProduct,
        id: 'test-protein-valid',
        name: 'Test Whey Protein',
        type: ProductType.Proteine,
        price: 24,
        amount: 900,
        protein_per_100g: 75,
    },
    {
        ...baseProduct,
        id: 'test-creatine-valid',
        name: 'Test Creatine Monohydrate',
        type: ProductType.Creatine,
        price: 18,
        amount: 500,
        creatine_per_100g: 100,
    },
    {
        ...baseProduct,
        id: 'test-weight-gainer-valid',
        name: 'Test Weight Gainer',
        type: ProductType.WeightGainer,
        price: 32,
        amount: 2500,
        protein_per_100g: 20,
        calories_per_100g: 380,
    },
    {
        ...baseProduct,
        id: 'test-preworkout-valid',
        name: 'Test Preworkout',
        type: ProductType.Preworkout,
        price: 29.99,
        amount: 300,
        dose: 10,
        caffeine_per_100g: 3000,
    },
    {
        ...baseProduct,
        id: 'test-preworkout-ingredient-valid',
        name: 'Test Citrulline Ingredient',
        type: ProductType.PreworkoutIngredient,
        price: 12,
        amount: 200,
        ingredients: [{ name: 'Citrulline malate', amount: 6000 }],
    },
    {
        ...baseProduct,
        id: 'test-vitamins-zero-amount-valid-price',
        name: 'Test Vitamins Missing Amount',
        type: ProductType.Vitamins,
        price: 9.99,
        amount: 0,
    },
    {
        ...baseProduct,
        id: 'test-food-zero-amount-valid-price',
        name: 'Test Protein Bar Missing Amount',
        type: ProductType.Food,
        price: 4.5,
        amount: 0,
    },
    {
        ...baseProduct,
        id: 'test-zero-price-warning',
        name: 'Test Scrape Missed Price',
        type: ProductType.Other,
        price: 0,
        amount: 100,
    },
    {
        ...baseProduct,
        id: 'test-percentage-discount',
        name: 'Test Percentage Discount',
        type: ProductType.Proteine,
        price: 20,
        amount: 1000,
        protein_per_100g: 80,
        discount_type: DiscountType.Percentage,
        discount_value: 10,
    },
    {
        ...baseProduct,
        id: 'test-fixed-discount',
        name: 'Test Fixed Discount',
        type: ProductType.Creatine,
        price: 15,
        amount: 300,
        creatine_per_100g: 100,
        discount_type: DiscountType.Fixed,
        discount_value: 5,
    },
];
